import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ClientOnly from '@/components/ClientOnly'
import Container from '@/components/navbar/Container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-orange-100 text-orange-600'>
      <body className={inter.className}>
        <ClientOnly>
          <Navbar />
        </ClientOnly>
        <div>
          <Container>
            {children}
          </Container>
        </div>
      </body>
    </html>
  )
}
